services:
  pm2-log-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pm2-log-viewer
    ports:
      - "8102:8001"
    volumes:
      # Monte o diretório de logs do host no container
      - /root/.pm2/logs:/app/logs:ro
    environment:
      - PORT=8001
      - TZ=America/Sao_Paulo
      - LOG_DIR=/app/logs
    restart: unless-stopped
    networks:
      - log-viewer-network
    labels:
      - "com.docker.compose.project=pm2-log-viewer"
      - "description=PM2 Log Viewer - Web interface for viewing PM2 logs"

networks:
  log-viewer-network:
    driver: bridge
